[package]
name = "sptune"
description = "A terminal user interface for Spotify"
keywords = ["spotify", "tui", "cli", "terminal"]
categories = ["command-line-utilities"]
version = "0.1.1"
authors = ["Proxy"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0.43"
rspotify = { version = "0.16.1", default-features = true }
ratatui = { version = "0.30.2", default-features = false, features = ["crossterm"] }
serde_yml = "0.0.13"
dirs = "6.0.0"
clap = "4.6.5"
unicode-width = "0.2.2"
arboard = "3.6.1"
crossterm = "0.29.0"
tokio = { version = "1.53.1", features = ["full"] }
reqwest = { version = "0.13", features = ["json"] }
chrono = "0.4"
futures = "0.3"
clap_complete = "4.6.5"


[patch.crates-io]
rspotify-model = { path = "vendor/rspotify-model" }

[[bin]]
bench = false
path = "src/main.rs"
name = "sptune"
